### ISSUE TITLE
Play Audio Clip from code 

### ISSUE THREAD

**Issue by Avatarchik** [Linerichka/SoundSystem-With-Eazy-Sound-Manager#6]
Can I play sound from code?

**Comment by Linerichka** [comment]
You can rely on the [documentation](https://github.com/Linerichka/SoundSystem-With-Eazy-Sound-Manager/blob/main/Assets/Lineri/SoundSystem/SoundSystem/Docs/Manual/EN.pdf) to get information about this.
You need to create a new class and inherit from the "SoundPocketManager" class. In your class, you can implement the logic you need and use the methods declared in the "SoundPocketManager" class as "xxxxHandler", these methods control the "SoundPocket" class (or several classes if there is more than one on the object) that will be received from the GameObject assigned in the "SoundPocket" field. This class will be derived from the "MonoBehaviour" class, so you can assign it to the GameObject and perform the operations you need. 
In addition, you can also directly affect the "SoundPocket" class through public methods (for example, the "Play" method to start playing a queue of clips assigned to this "SoundPocket" class) and changing the values of public variables.
