### ISSUE TITLE
Not work  PlayAllClipsTogether Music

### ISSUE THREAD

**Issue by Avatarchik** [Linerichka/SoundSystem-With-Eazy-Sound-Manager#7]

**Comment by Linerichka** [comment]
This can happen if the "OnlyOnePlayableMusicClip" variable in the EazySoundManager class is set to "true", in this case, when trying to start a new music clip when there is another music clip that is currently playing, the playing clip will be stopped and the new one will be started. Please make sure that this variable is set to "false", you can set it to this position either by editing the code of the EazySoundManager class itself, or from other classes by simply changing its value.
![image](https://github.com/Linerichka/SoundSystem-With-Eazy-Sound-Manager/assets/130474996/3f4c5256-9541-4750-9030-c3d0d846546f)
